const data = {
  availableInterests: [
    "Advocacy and Human Rights",
    "Animals",
    "Arts & Culture",
    "Children & Youth",
    "Community",
    "Counseling",
    "Crisis Support",
    "Disaster Relief",
    "Education & Literacy",
    "Emergency & Safety",
    "Employment",
    "Environment",
    "Faith-based",
    "Health & Medicine",
    "Homeless & Housing",
    "Human Services",
    "Hunger",
    "Immigrants & Refugees",
    "International",
    "Justice & Legal",
    "LGBTQ",
    "Media",
    "Mentoring",
    "People with Disabilities",
    "Politics",
    "Seniors",
    "Sports & Recreation",
    "Technology",
    "Veteran Support",
    "Women"
  ],
  availableSkills: [
    "Clerical",
    "Coaching",
    "Communications",
    "Computers",
    "Design & Graphical Arts",
    "Electrical",
    "Engineering",
    "Event Management",
    "Finance",
    "Fund Raising",
    "Food Services",
    "Health Care",
    "Hobbies & Crafts",
    "Human Resources",
    "IT Infrastructure",
    "Landscaping",
    "Legal",
    "Logistics",
    "Marketing",
    "Music",
    "Non-Profit Development",
    "Performing Arts",
    "Plumbing",
    "Strategic Planning",
    "Software Development",
    "Trades",
    "Tutor",
    "Web Development"
  ]
};

export default data;
